n = int(input('Digite um número para saber sua tabuada: '))
n1 = n * 1
n2 = n * 2
n3 = n * 3
n4 = n * 4
n5 = n * 5
n6 = n * 6
n7 = n * 7
n8 = n * 8
n9 = n * 9
n10 = n * 10
print('A taboada de {} é:\n'
      '{} * 1 = {} \n'
      '{} * 2 = {}\n'
      '{} * 3 = {}\n'
      '{} * 4 = {}\n'
      '{} * 5 = {}\n'
      '{} * 6 = {}\n'
      '{} * 7 = {}\n'
      '{} * 8 = {}\n'
      '{} * 9 = {}\n'
      '{} * 10 = {}' . format(n, n, n1, n, n2, n, n3, n, n4, n, n5, n, n6, n, n7, n, n8, n, n9, n, n10))