n = input('Digite algo: ')
print('O Tipo desse valor é {}', type(n))
print('Só tem espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalnum())
print('É Alfanumérico?', n.isalnum())
print('Está em letras maiúsculas?', n.isupper())
print('Está em letras minúsculoas?', n.islower())
print('Está capitalizada?', n.istitle())
